// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingPlanner.Infrastructure.Data;

#nullable disable

namespace WeddingPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeddingPlanner.Core.Models.Bend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("JeDJ")
                        .HasColumnType("bit");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId")
                        .IsUnique();

                    b.ToTable("Bendovi");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.CijenaBenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BendId")
                        .HasColumnType("int");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Kategorija")
                        .HasColumnType("int");

                    b.Property<int>("TrajanjeH")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BendId");

                    b.ToTable("CijeneBendova");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Cvjecara", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId")
                        .IsUnique();

                    b.ToTable("Cvjecare");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.CvjecarskiAranzman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CvjecaraId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CvjecaraId");

                    b.ToTable("CvjecarskiAranzmani");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Dogadaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDogadaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivPara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipVjencanjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipVjencanjaId");

                    b.ToTable("Dogadaji");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DodatniPodaci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kontakt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Provizija")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Partneri");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BendId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zanr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BendId");

                    b.ToTable("Playliste");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.RacunStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DogadajId")
                        .HasColumnType("int");

                    b.Property<decimal>("IznosOsnovni")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Provizija")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogadajId");

                    b.ToTable("RacunStavke");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.RestaurantSalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojStolova")
                        .HasColumnType("int");

                    b.Property<decimal>("CijenaPoOsobi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CijenaSale")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MjestaPoBrojStolu")
                        .HasColumnType("int");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("TipUsluge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId")
                        .IsUnique();

                    b.ToTable("RestaurantSaloni");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BendId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("DogadajId")
                        .HasColumnType("int");

                    b.Property<bool>("Potvrdena")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BendId");

                    b.HasIndex("DogadajId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Slasticarnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId")
                        .IsUnique();

                    b.ToTable("Slasticarnice");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.SlasticarskaStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Kategorija")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlasticarnicaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlasticarnicaId");

                    b.ToTable("SlasticarskeStavke");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.TipVjencanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoviVjencanja");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Bend", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.Partner", "Partner")
                        .WithOne("Bend")
                        .HasForeignKey("WeddingPlanner.Core.Models.Bend", "PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.CijenaBenda", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.Bend", "Bend")
                        .WithMany("Cijene")
                        .HasForeignKey("BendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bend");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Cvjecara", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.Partner", "Partner")
                        .WithOne("Cvjecara")
                        .HasForeignKey("WeddingPlanner.Core.Models.Cvjecara", "PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.CvjecarskiAranzman", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.Cvjecara", "Cvjecara")
                        .WithMany("Aranzmani")
                        .HasForeignKey("CvjecaraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cvjecara");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Dogadaj", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.TipVjencanja", "TipVjencanja")
                        .WithMany("Dogadaji")
                        .HasForeignKey("TipVjencanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipVjencanja");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Playlist", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.Bend", "Bend")
                        .WithMany("Playliste")
                        .HasForeignKey("BendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bend");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.RacunStavka", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.Dogadaj", "Dogadaj")
                        .WithMany("RacunStavke")
                        .HasForeignKey("DogadajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dogadaj");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.RestaurantSalon", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.Partner", "Partner")
                        .WithOne("RestaurantSalon")
                        .HasForeignKey("WeddingPlanner.Core.Models.RestaurantSalon", "PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Rezervacija", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.Bend", "Bend")
                        .WithMany("Rezervacije")
                        .HasForeignKey("BendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeddingPlanner.Core.Models.Dogadaj", "Dogadaj")
                        .WithMany("Rezervacije")
                        .HasForeignKey("DogadajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bend");

                    b.Navigation("Dogadaj");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Slasticarnica", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.Partner", "Partner")
                        .WithOne("Slasticarnica")
                        .HasForeignKey("WeddingPlanner.Core.Models.Slasticarnica", "PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.SlasticarskaStavka", b =>
                {
                    b.HasOne("WeddingPlanner.Core.Models.Slasticarnica", "Slasticarnica")
                        .WithMany("Stavke")
                        .HasForeignKey("SlasticarnicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slasticarnica");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Bend", b =>
                {
                    b.Navigation("Cijene");

                    b.Navigation("Playliste");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Cvjecara", b =>
                {
                    b.Navigation("Aranzmani");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Dogadaj", b =>
                {
                    b.Navigation("RacunStavke");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Partner", b =>
                {
                    b.Navigation("Bend");

                    b.Navigation("Cvjecara");

                    b.Navigation("RestaurantSalon");

                    b.Navigation("Slasticarnica");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.Slasticarnica", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("WeddingPlanner.Core.Models.TipVjencanja", b =>
                {
                    b.Navigation("Dogadaji");
                });
#pragma warning restore 612, 618
        }
    }
}
